### ISSUE TITLE
JSE-Drop fails if tool stdout/stderr contains non-ASCII characters?

### ISSUE THREAD

**Issue by pjbriggs** [pjbriggs/ansible-palfinder-galaxy#41]
It appears that the JSE-Drop interface fails when processing the stdout and/or stderr for a job if the tool outputs a non-ASCII character, e.g.:

    Traceback (most recent call last):
      File "lib/galaxy/jobs/runners/jse_drop_runner.py", line 372, in finish_job
        job_state.job_wrapper.finish(stdout,stderr,exit_code)
      File "lib/galaxy/jobs/__init__.py", line 1301, in finish
        dataset.datatype.set_meta(dataset, overwrite=False)
      File "lib/galaxy/datatypes/interval.py", line 426, in set_meta
        Tabular.set_meta(self, dataset, overwrite=overwrite, skip=i)
      File "lib/galaxy/datatypes/tabular.py", line 337, in set_meta
        line = dataset_fh.readline()
      File "/XXXXXXXXXXXXXXXXXXXXXXXXXX/galaxy-dist/.venv/lib/python2.7/codecs.py", line 296, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf8' codec can't decode byte 0xab in position 3: invalid start byte

**Comment by pjbriggs** [comment]
Possible fix here:

https://stackoverflow.com/a/22216798/579925

i.e. convert the stdout and stderr to UTF-8 using something like:

    a.encode('utf-8').strip()

**Comment by pjbriggs** [comment]
This turned out not to be a problem with the stdout/stderr, but with Galaxy failing to set metadata on one of the tool outputs (described here https://github.com/damiantarasek/snp2hla-p/pull/4).
