### ISSUE TITLE
JSE-Drop can't handle qacct exit_status with multiple values

### ISSUE THREAD

**Issue by pjbriggs** [pjbriggs/ansible-palfinder-galaxy#50]
When `qacct` output includes a non-standard `exit_status` value such as:

    exit_status  137                  (Killed)

or 

    exit_status  255                  (Unknown signal 127)

instead of just e.g.

    exit_status  2

then JSE-Drop cannot handle this correctly:

    galaxy.jobs.runners ERROR 2019-07-29 09:33:00,876 [p:6738,w:0,m:1][JSEDropJobRunner.work_thread-1] (37622) Unhandled exception calling finish_job
    Traceback (most recent call last):
      File "lib/galaxy/jobs/runners/__init__.py", line 113, in run_next
    method(arg)
      File "lib/galaxy/jobs/runners/jse_drop_runner.py", line 341, in finish_job
        exit_code = int(jse_drop.qacct(external_job_id)['exit_status'])
    ValueError: invalid literal for int() with base 10: '255                  (Unknown signal 127)'

**Comment by pjbriggs** [comment]
Should be fixed by PR #51.
