### ISSUE TITLE
JSE-Drop runner is unable to delete jobs in Galaxy 19.05

### ISSUE THREAD

**Issue by pjbriggs** [pjbriggs/ansible-palfinder-galaxy#52]
JSE-Drop runner is unable to delete jobs in Galaxy 19.05 - the following error is found in the log and the `.qdel` file isn't written to stop the job:

    Traceback (most recent call last):
      File "lib/galaxy/jobs/handler.py", line 867, in monitor
        self.monitor_step()
      File "lib/galaxy/jobs/handler.py", line 921, in monitor_step
        self.dispatcher.stop(job, job_wrapper)
      File "lib/galaxy/jobs/handler.py", line 1002, in stop
        self.job_runners[runner_name].stop_job(job_wrapper)
      File "lib/galaxy/jobs/runners/jse_drop_runner.py", line 257, in stop_job
        job_name = job.get_job_runner_external_id()
    AttributeError: 'JobWrapper' object has no attribute 'get_job_runner_external_id'

(It's not clear yet if this only affects jobs in the `qw` state on the cluster.)

**Comment by pjbriggs** [comment]
Fixed by PR #53.
